define([], function() {
  return {
    "PropertyPaneDescription": "Aggregated Calendar App",
    "BasicGroupName": "Dynamic Properties",
    "DescriptionFieldLabel": "Description Field",
    "AppLocalEnvironmentSharePoint": "The app is running on your local environment as SharePoint web part",
    "AppLocalEnvironmentTeams": "The app is running on your local environment as Microsoft Teams app",
    "AppLocalEnvironmentOffice": "The app is running on your local environment in office.com",
    "AppLocalEnvironmentOutlook": "The app is running on your local environment in Outlook",
    "AppSharePointEnvironment": "The app is running on SharePoint page",
    "AppTeamsTabEnvironment": "The app is running in Microsoft Teams",
    "AppOfficeEnvironment": "The app is running in office.com",
    "AppOutlookEnvironment": "The app is running in Outlook",
    "SelectCalendarLabel": "Add Calendars",
    "HeaderFieldLabel": "App Header Value",
    "WebPartNotConfigured": "Webpart is not configured. Please configure webpart by Editing the page.",
    "StartTimeLabel": "Start Time : ",
    "EndTimeLabel": "End Time : ",
    "LocationLabel": "Location : ",
    "CategoryLabel": "Category : ",
    "SelectDateFormatFieldLabel": "Select Date & Time Format",
    "ShowWeekendsFieldLabel": "Show Weekends",
    "OnTextFieldLabel": "On",
    "OffTextFieldLabel": "Off",
    "DefautlViewFieldLabel": "Default Calendar View",
    "ShowLegendFieldLabel": "Show Legend",
    "AvailableViewFieldLabel": "Select Available Views",
    "HeightFieldLabel":"Enter Calendar Height",
    "EmployeeNameLabel": "Employee Name",
    // "LocationLabel": "Location",
    "DescriptionTextAreaLabel": "Description",
    "CategoryTypeLabel": "Category",
    "AllDayEventLabel": "All Day Event",
    "RecurrenceLabel": "Recurrence",
    "CommentsLabel": "Comments",
    "ApprovedLabel": "Approved",
    "ApproverCommentsLabel": "Approver Comments",
    "DepartmentLabel": "Department",
    "LeaveCategoryLabel": "Leave Category",
    "TitleLabel": "Title",
    "DefaultView": "Default Calendar View",
    "everyFormat": "Every {0} ",
    "weekDayLabel": "Weekday",
    "everySecondFormat": "Every {0} ",
    "everyNthFormat": "Every {0} ",
    "onTheDayFormat": "on the {0}th day",
    "onTheLabel": "on the",
    "theSuffix": "",
    "yearLabel": "year",
    "theNthOfMonthFormat": "on {0} {1}",
    "onTheDayTypeFormat": "on the {0} {1}",
    "Saturday": "Saturday",
    "Friday": "Friday",
    "Thursday": "Thursday",
    "Wednesday": "Wednesday",
    "Tuesday": "Tuesday",
    "Monday": "Monday",
    "Sunday": "Sunday",
    "lastLabel": "last",
    "fourthLabel": "fourth",
    "thirdLabel": "third",
    "secondLabel": "second",
    "firstLabel": "first",
    "dayLable": "Day",
    "onLabel": "On",
    "monthLabel": "Month",
    "weekLabel": "Week",
    "weekEndDay": "Weekend Day",
    "December": "December",
    "November": "November",
    "October": "October",
    "September": "September",
    "August": "August",
    "July": "July",
    "June": "June",
    "May": "May",
    "April": "April",
    "March": "March",
    "February": "February",
    "January": "January",
    "Jan":"Jan",
    "Feb":"Feb",
    "Mar":"Mar",
    "Apr":"Apr",
    "May":"May",
    "Jun":"Jun",
    "Jul":"Jul",
    "Aug":"Aug",
    "Sep":"Sep",
    "Oct":"Oct",
    "Nov":"Nov",
    "Dez":"Dez",
    "InvalidDateFormat": "Invalid date format.",
    "IsRequired": "Field is required.",
    "CloseDate": "Close date picker",
    "NextYear": "Go to next year",
    "PrevYear": "Go to previous year",
    "NextMonth": "Go to next month",
    "PrevMonth": "Go to previous month",
    "GoToDay": "Go to today",
    "ShortDay_Saunday": "S",
    "ShortDay_Friday": "F",
    "ShortDay_Tursday": "T",
    "ShortDay_W": "W",
    "ShortDay_T": "T",
    "ShortDay_M": "M",
    "ShortDay_S": "S",
    "LoadingEventsLabel":"Loading events..."
  }
});